### ISSUE TITLE
Plugin doesn't seem to work with latest builds of WebStorm 2024.3

### ISSUE THREAD

**Issue by dannybloe** [ivanovych666/intellij-json-sorter-plugin#16] opened 2024-10-09 10:02 UTC
Using this:
WebStorm 2024.3 EAP
Build #WS-243.18137.24, built on October 2, 2024

Would be nice to fix that 🙂

**Comment by ivanovych666** [comment] 2024-10-10 14:59
@dannybloe Thank you for the report. I found the issue and as for me it looks like a bug in EAP, but maybe they changed their library, but I can't find any information about this yet. In any case, I have a fix, and I'm going to release the update soon.

**Comment by ivanovych666** [comment] 2024-10-11 09:07
The issue is fixed in v2.1.1.

**Closed as completed by ivanovych666** 2024-10-11 09:07 UTC

**Comment by dannybloe** [comment] 2024-10-14 06:12
You're the best! Thanks. Love the plug-in!
