### ISSUE TITLE
Would be nice on *.arb files

### ISSUE THREAD

**Issue by JeanChristophePal** [ivanovych666/intellij-json-sorter-plugin#10] opened 2020-04-09 15:46 UTC
*.arb are json (use in Flutter for intl translation), maybe it's just an extension to add somewhere.

Arb file:
https://github.com/google/app-resource-bundle/wiki/ApplicationResourceBundleSpecification

Flutter intl:
https://flutter.dev/docs/development/accessibility-and-localization/internationalization#appendix-using-the-dart-intl-tools

Intellij intl plugin example
https://plugins.jetbrains.com/plugin/13666-flutter-intl

**Comment by ivanovych666** [comment] 2020-04-09 16:02
Duplicate of #3

**Closed by ivanovych666** 2020-04-09 16:02 UTC
